# Generated by Django 5.1.1 on 2024-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_termino',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluída', 'Concluída')], max_length=50),
        ),
    ]
