# Generated by Django 5.1.1 on 2024-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_usuario_remove_projeto_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Colaborador', 'Colaborador')], max_length=50),
        ),
    ]
